name: DisguiseCookie

author: SentryoZVN
description: A generic Slimefun4-Addon

main: me.sentryozvn.disguisecookies.DisguiseCookie

## You can change this to link to your website or repository. You can also remove this line if you want to.
website: https://github.com/TheBusyBiscuit/Slimefun4-Addon

## This is required and marks Slimefun as a plugin dependency.
depend: [Slimefun, LibsDisguises]

## This value is automatically replaced by the version specified in your pom.xml file, do not change this.
version: ${project.version}

## This is the minimum minecraft version required to run your plugin.
api-version: 1.16
